version: '3.8'
services:
  #web es el nombre que le dimos al servicio
  web:
    # busca en este archivo un dockerfile
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app

  redis:
    image: redis